project:
  type: website

website:
  title: "DevOps For Data Science"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: EDA
        href: eda.qmd
      - text: Model
        href: model.qmd
  site-url: https://binxiepeterson.github.io/test_R_devops/

format:
  html:
    theme: cosmo
    toc: true
